name: homerental_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
  - images/home_1.jfif
  - images/home_2.jfif
  - images/ksenia-balandina-RCF5KSWb7Ms-unsplash 1.png
  - images/pexels-expect-best-323780 1.png
  - images/IC_Bath.png
  - images/Vector.png
  - images/IC_Filter.png
  - images/Vector_white.png
  - images/IC_Bath_white.png
  - images/person.png
  - images/comment.png
  - images/gallery_1.jfif 
  - images/gallery_2.jfif 
  - images/gallery_3.jfif 
  - images/gallery_4.jfif