name: codex_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  highlight: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets : 
  - images/javafullstack.png
  - images/mernstack.png
  - images/personicon.png
  - images/java.png 