name: food
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.4
  firebase_auth: ^5.0.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.0.1
  flutter_stripe: ^10.1.0
  dio: ^5.5.0+1
  http:
  random_string: ^2.3.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.0
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets : 
  - images/
