name: codex_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - images/java-14-logo.png
   - images/Python-logo.png
   - images/Dart-logo.png
   - images/js-logo.png
   - images/mongodb.png
   - images/vs-logo.png
   - images/spring-logo.png
   - images/react-logo.png
   - images/maria.png
   - images/eclipse.png
   - images/hibernate-logo.png
   - images/git-img.png
   - images/github.png
   - images/mysql-img.png
